.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. digitalgold_qt test_digitalgold_qt
clean: FORCE
	$(MAKE) -C .. digitalgold_qt_clean test_digitalgold_qt_clean
check: FORCE
	$(MAKE) -C .. test_digitalgold_qt_check
digitalgold-qt digitalgold-qt.exe: FORCE
	 $(MAKE) -C .. digitalgold_qt
apk: FORCE
	$(MAKE) -C .. digitalgold_qt_apk
