.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. usdg_qt test_usdg_qt
clean: FORCE
	$(MAKE) -C .. usdg_qt_clean test_usdg_qt_clean
check: FORCE
	$(MAKE) -C .. test_usdg_qt_check
usdg-qt usdg-qt.exe: FORCE
	 $(MAKE) -C .. usdg_qt
apk: FORCE
	$(MAKE) -C .. usdg_qt_apk
